import type { Metadata } from "next";
import { Alan_Sans } from "next/font/google";
import "./globals.css";



const alanSans = Alan_Sans({
  variable: "--font-alan-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "zenith",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alanSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
