import type { Metadata } from "next";
import { Instrument_Serif, Alan_Sans } from "next/font/google";
import "./globals.css";

const alanSans = Alan_Sans({
  variable: "--font-alan",
  subsets: ["latin"],
  weight: ["400", "800"],
});
const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alanSans.variable} ${instrumentSerif.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
